# Definimos el tipo de base de datos
quarkus.datasource.db-kind=postgresql
# Usuario con el que se conecta a la base de datos
quarkus.datasource.username=postgres
# Password del usuario de conexion
quarkus.datasource.password=postgres
# URL de la conexión de la base de datos
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/pa2db2
# Sincronizar cuando hay una actualización en la entidad
quarkus.hibernate-orm.database.generation=update
# Se muestra el log en consola
quarkus.hibernate-orm.log.sql=true
# quarkus.hibernate-orm.sql-load-script=import.sql
quarkus.transaction-manager.default-transaction-timeout=PT30M